# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Ensure stdout/stderr are unbuffered
ENV PYTHONUNBUFFERED=1

# Start the MCP server
CMD ["python3", "main.py"]
